//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AegisFront.AegisLibraryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AegisLibraryServiceReference.ILibraryService")]
    public interface ILibraryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/AddBook", ReplyAction="http://tempuri.org/IBookService/AddBookResponse")]
        AegisLibraryService.Model.BookType AddBook(AegisLibraryService.Model.BookType book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/AddBook", ReplyAction="http://tempuri.org/IBookService/AddBookResponse")]
        System.Threading.Tasks.Task<AegisLibraryService.Model.BookType> AddBookAsync(AegisLibraryService.Model.BookType book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBook", ReplyAction="http://tempuri.org/IBookService/GetBookResponse")]
        AegisLibraryService.Model.BookType GetBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBook", ReplyAction="http://tempuri.org/IBookService/GetBookResponse")]
        System.Threading.Tasks.Task<AegisLibraryService.Model.BookType> GetBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
        AegisLibraryService.Model.BookType[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
        System.Threading.Tasks.Task<AegisLibraryService.Model.BookType[]> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/AddAuthor", ReplyAction="http://tempuri.org/IAuthorService/AddAuthorResponse")]
        AegisLibraryService.Model.AuthorType AddAuthor(AegisLibraryService.Model.AuthorType author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/AddAuthor", ReplyAction="http://tempuri.org/IAuthorService/AddAuthorResponse")]
        System.Threading.Tasks.Task<AegisLibraryService.Model.AuthorType> AddAuthorAsync(AegisLibraryService.Model.AuthorType author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/GetAuthor", ReplyAction="http://tempuri.org/IAuthorService/GetAuthorResponse")]
        AegisLibraryService.Model.AuthorType GetAuthor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/GetAuthor", ReplyAction="http://tempuri.org/IAuthorService/GetAuthorResponse")]
        System.Threading.Tasks.Task<AegisLibraryService.Model.AuthorType> GetAuthorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/GetAllAuthors", ReplyAction="http://tempuri.org/IAuthorService/GetAllAuthorsResponse")]
        AegisLibraryService.Model.AuthorType[] GetAllAuthors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/GetAllAuthors", ReplyAction="http://tempuri.org/IAuthorService/GetAllAuthorsResponse")]
        System.Threading.Tasks.Task<AegisLibraryService.Model.AuthorType[]> GetAllAuthorsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryServiceChannel : AegisFront.AegisLibraryServiceReference.ILibraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryServiceClient : System.ServiceModel.ClientBase<AegisFront.AegisLibraryServiceReference.ILibraryService>, AegisFront.AegisLibraryServiceReference.ILibraryService {
        
        public LibraryServiceClient() {
        }
        
        public LibraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AegisLibraryService.Model.BookType AddBook(AegisLibraryService.Model.BookType book) {
            return base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task<AegisLibraryService.Model.BookType> AddBookAsync(AegisLibraryService.Model.BookType book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public AegisLibraryService.Model.BookType GetBook(int id) {
            return base.Channel.GetBook(id);
        }
        
        public System.Threading.Tasks.Task<AegisLibraryService.Model.BookType> GetBookAsync(int id) {
            return base.Channel.GetBookAsync(id);
        }
        
        public AegisLibraryService.Model.BookType[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<AegisLibraryService.Model.BookType[]> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public AegisLibraryService.Model.AuthorType AddAuthor(AegisLibraryService.Model.AuthorType author) {
            return base.Channel.AddAuthor(author);
        }
        
        public System.Threading.Tasks.Task<AegisLibraryService.Model.AuthorType> AddAuthorAsync(AegisLibraryService.Model.AuthorType author) {
            return base.Channel.AddAuthorAsync(author);
        }
        
        public AegisLibraryService.Model.AuthorType GetAuthor(int id) {
            return base.Channel.GetAuthor(id);
        }
        
        public System.Threading.Tasks.Task<AegisLibraryService.Model.AuthorType> GetAuthorAsync(int id) {
            return base.Channel.GetAuthorAsync(id);
        }
        
        public AegisLibraryService.Model.AuthorType[] GetAllAuthors() {
            return base.Channel.GetAllAuthors();
        }
        
        public System.Threading.Tasks.Task<AegisLibraryService.Model.AuthorType[]> GetAllAuthorsAsync() {
            return base.Channel.GetAllAuthorsAsync();
        }
    }
}
